package com.sumadhura.transdao;

import java.sql.Date;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.servlet.http.HttpServletRequest;

import org.springframework.jdbc.core.JdbcTemplate;

import com.sumadhura.bean.ContractorQSBillBean;
import com.sumadhura.bean.ContractorTaxReportBean;
import com.sumadhura.bean.PaymentBean;
import com.sumadhura.bean.PaymentModesBean;
import com.sumadhura.bean.PurchaseTaxReportBean;
import com.sumadhura.bean.VendorDetails;
import com.sumadhura.bean.ViewIndentIssueDetailsBean;
import com.sumadhura.dto.PaymentDto;

public interface PaymentProcessDao {

	
	public List<PaymentBean> getInvoiceDetails(String siteId,Map<String,String> reqParamsMap, String selectAll, String ispaymentReqDateChecked, boolean isItFirstRequest);
	public int savePaymentTable(PaymentDto objPaymentDto,int PaymentId);
	public int savePaymentProcessDtlsTable(PaymentDto objPaymentDto,int intPaymentId,int paymentEntrySeqId);
	public int savePaymentApproveRejectTable(PaymentDto objPaymentDto,int intPaymentId,int intPaymentDetailsId);
	public int getPaymentId();
	public int getPaymentDetailsId();
	public List<PaymentBean> getPaymentApprovalDetails(String siteId,String user_id);
	public String getPendingEmpId(String strUserId, String session_siteId);
	public int saveApprovalDetails(String paymentId,String strUserId,String comments,String pendingDetailsId,String site_id);
	public int  saveRejectDetails(String paymentId,String strUserId,String comments,String pendingDetailsId,String site_id);
	public int saveChangedDetails(PaymentBean objPaymentBean,String paymentChangedType);
	public int UpDatePaymentDetails(String paymentDetailsId,double changedAmount);
	public String getDeptId(String strUserId,String session_siteId);
	public int updateRequestedPaymentEmpId(String paymentDetailsId,String pendingEmpId);
	public int updatePaymentDetailsDate(String paymentDetailsId,String  changedRequestedDate);
	public int getSiteWisePaymentNo(String site_id);
	public int saveAccountsDeptTable(PaymentBean objPaymentBean);
	public int updateRequestedPaymentDeptId(String paymentDetailsId, String deptEmpId);
	public List<PaymentBean> getPODetails(String siteId,Map<String,String> reqParamsMap, String selectAll);
	public List<PaymentBean> getAccDeptPaymentApprovalDetails(String siteId, String user_id, Map<String, String> map);
	
	public List<PaymentBean> getAccDeptPaymentPendingDetails(String strUserId, Map<String, String> map);
	public int insertTempPaymentTransactionsTbl(PaymentDto objPaymentDto, int tempPaymentId);
	public String getApproverEmpIdInAccounts(String strEmpId);
	public int updateAccDeptPaymentProcsstbl(PaymentDto objPaymentDto);
	public int updateTempPaymentTransactionsTbl(PaymentDto objPaymentDto,String strPendingEmpId);
	public int insertPaymentTransactionsTbl(PaymentDto objPaymentDto, int intPaymentTransactionId);
	public int updatePaymentDetailsAdjustAmount(String paymentDetailsId, double doubleAdjustAmountFromAdvance);
	public String getRemainingAmountInAdvance(String poNo);
	public int updateReqUptoInAccPayment(String paymentId, String actualRequestedAmount,String changedRequestedAmount, double actualDoubleAdjustAmountFromAdvance, double doubleAdjustAmountFromAdvance);
	public int updateIntiateAmountInAdvancePaymentPO(String poNo, double actualDoubleAdjustAmountFromAdvance,double doubleAdjustAmountFromAdvance);
	public int updateAdvancePaymentPoTable(String poNo, double doubleAdjustAmountFromAdvance);
	public int insertPoHistory(PaymentDto objPaymentDto);
	public int insertInvoiceHistory(PaymentDto objPaymentDto, int intPaymentTransactionId);
	public int updatePaymentReqUptoInAccPaymentTable(PaymentDto objPaymentDto);
	public int insertPaidAmountInAdvancePaymentPoTable(PaymentDto objPaymentDto);
	public String getLowerEmpIdInAccounts(String strEmpId);
	//public List<String> getPaymentInitiatorInAccounts();
	public int revertPendingApprovalToLowerEmployee(String strLowerEmpId, int intTempPaymentTransactionId, String remarks);
	public int updateRowInAccTempPaymentTransactions(int intTempPaymentTransactionId, String remarks,int intPaymentDetailsId);
	public int updateIntiateAmountInAccDeptPaymentProcesstbl(String requestedAmount, int intAccDeptPaymentProcessId, double actualDoubleAdjustAmountFromAdvance);
	public int getAccTempPaymentTransactionSeqNo();
	public int saveAccountsApproveRejectTable(PaymentDto objPaymentDto, int intAccDeptPaymentProcessId,int intTempPaymentTransactionId);
	public int saveAccountApprovalDetails(int intAccDeptPaymentProcessId, String strUserId, String comments, int intTempPaymentTransactionId,String site_id);
	public int saveAccountRejectDetails(int intAccDeptPaymentProcessId, String strEmpId, String comments,int intTempPaymentTransactionId, String siteId);
	public int saveAccountChangedDetails(PaymentBean objPaymentBean, String string);
	public int updateRequestedPaymentDeptIdOnAccDeptReject(String paymentDetailsId, String pendingEmpId);
	public int removeRowInAccDeptPmtProcessTbl(int intAccDeptPaymentProcessId);
	public int updateRefNoInAccDeptTransaction(String strRefNo, int intPaymentTransactionId, String paymentMode, String paymentDate);
	public List<PaymentBean> getAccDeptPaymentDetailsToUpdate(String siteId, String user_id, String fromDate, String toDate, String vendorId, String invoiceNumber, String poNumber, String dropdown_SiteId,String selectAll);
	public int UpDatePaymentDetailsRemarks(String paymentDetailsId, String remarks);
	public int updateReqUptoInAccPaymentOnReject(String paymentId, String actualRequestedAmount, double actualDoubleAdjustAmountFromAdvance);
	public int updateIntiateAmountInAdvancePaymentPOOnReject(String poNo, double actualDoubleAdjustAmountFromAdvance);
	public int setInactiveAccPaymentAfterCheck(int intPaymentId);
	public int updateRefNoInInvoiceHistory(String strRefNo, String paymentMode, int intPaymentTransactionId);
	public int getIntPaymentTransactionId();
	public int insertInvoiceHistoryAdjust(PaymentDto objPaymentDto, int intPaymentTransactionId);
	public String[] getPaymentApproverEmailId(String strUserId,String session_siteId);
	public List<PaymentModesBean> getPaymentModes();
	public VendorDetails getVendorAccountDetails(String vendorId);
	public List<PaymentBean> getPaymentApprovalDetailsForMail(String siteId, String user_id, String groupOfPaymentDetailsId);
	public void setJdbcTemplate(JdbcTemplate jdbcTemplate);
	public String[] getAllSiteLevelEmails(String siteId);
	public int setInactiveRowInAccDeptPmtProcessTbl(int intAccDeptPaymentProcessId);
	public int UpDatePaymentDetailsRemarksAndSetInactive(String paymentDetailsId, String remarks);
	public String getSiteAddressByUsingSiteId(String reqSiteId);
	public List<PaymentBean> getPaymentAccountsFirstLevelApprovalDetailsForMail(String strUserId,String groupOfPaymentDetailsId);
	public String[] getEmailsOfEmpByDeptId(String pendingDeptId);
	public String getEmpNameByEmpId(String empId);
	public String getSiteNameBySiteId(String siteId);
	public String getApproverDeptIdInAccounts(String strEmpId);
	public String[] getEmailsOfEmpByEmpId(String empId);
	public String[] getEmailsOfEmployeesInLowerDeptOfThisEmployee(String user_id);
	public String[] getEmailsOfEmployeesInAllLowerDeptOfThisEmployeeInSiteLevel(String user_id,String session_siteId);
	public int insertInACC_PAYMENT(PaymentBean objPaymentBean, int paymentId);
	public int insertInACC_PAYMENT_DTLS(PaymentBean objPaymentBean, int paymentId, int paymentEntryDetailsSeqID);
	public int insertInACC_ACCOUNTS_DEPT_PMT_PROSS(PaymentBean objPaymentBean, int accDeptPaymentProssSeqNo);
	public int insertInACC_TEMP_PAYMENT_TRANSACTIONS(PaymentBean objPaymentBean, int tempPaymentId);
	public int insertInACC_PAYMENT_TRANSACTIONS(PaymentBean objPaymentBean, int intPaymentTransactionId);
	public int insertInvoiceHistory(PaymentBean objPaymentBean, int intPaymentTransactionId);
	public int insertPoHistory(PaymentBean objPaymentBean);
	public int insertPaidAmountInAdvancePaymentPoTable(PaymentBean objPaymentBean);
	public int getAccDeptPaymentProssSeqNo();
	public int getPaymentIdByInvoiceNo(PaymentBean objPaymentBean);
	public int updateACC_PAYMENT(PaymentBean objPaymentBean, int paymentId);
	public int getIndentEntryIdByInvoiceNo(String invoiceNo, String siteId, String vendorId);
	public int updatePaymentTable(PaymentDto objPaymentDto);
	public int savePaymentTableOnPoAdvance(PaymentDto objPaymentDto, int PaymentId);
	public int updatePaymentTableOnPoAdvance(PaymentDto objPaymentDto);
	public List<PaymentBean> getInvoiceDetailsForOldPayments(String siteId, Map<String, String> reqParamsMap);
	public int savePaymentProcessDtlsTableOnPoAdvance(PaymentDto objPaymentDto, int intPaymentId, int paymentEntrySeqId);
	public int updatePoAdvanceTable(PaymentDto objPaymentDto);
	public int updatePaymentReqUptoAndPaymentDoneUptoInAccPaymentTable(PaymentDto objPaymentDto);
	public List<PaymentBean> getContractorBillReqDetails(String user_Id,String site_id, Map<String,String> reqParamsMap);
	public int saveContractorBillPaymentProcessDtls(PaymentBean objPaymentBean,int acc_pross_pmt_Id,String pendingDeptId);
	public String getPendingContractorEmp(String strUserId);
	public String getPendingContractorDeptId(String strUserId, String session_site_id);
	public int updateContractorBillPayment(PaymentBean objPaymentBean,String pendingEmpId);
	public String[] getEmailsOfEmpByEmpIdAndEmailsOfEmployeesInAllLowerDeptOfThisEmployeeInSiteLevel(String user_id,String session_siteId);
	public String[] getEmailsOfEmployeesInLowerDeptOfThisEmployeeInSiteLevel(List<String> emailList, String user_id, String siteId);
	public int returnPaymentIdIfThereIsAnyRowWithCurrentPO_NUMBER(PaymentDto objPaymentDto);
	public int updatePaymentTableOnPoNumber(PaymentDto objPaymentDto, int poPaymentId);
	public boolean checkingIsRequestAmountExceedLimitOfPoAmount(double doubleAmountToBeReleased, int poPaymentId);
	public boolean checkingIsTotalPoAmountIsPaid(String poNo, double reqAmount);
	public int insertCntPaymentApprRejDetail(PaymentBean objPaymentBean, String operType);
	public List<PaymentBean> getLocalPurchaseInvoiceDetails(String siteId, Map<String, String> reqParamsMap, String selectAll);
	public int updateRemainingAdvanceAmountInAdvancePaymentPoTable(PaymentBean objPaymentBean);
	public Map<String, PaymentBean> getInvoiceNoAndPoNoByPaymentDtlsId(List<String> alreadyApprovedList);
	public String checkIsTaxInvoiceIsSubmitedOrNot(String strVendorId,
			String indentEntryId, String strInvoiceNo, String session_siteId);
	public List<PurchaseTaxReportBean> getPurchaseTaxReport(Map<String, String> requestMap);
	public String getPendingDeptId(String strUserId, String session_siteId);
	public List<String> getEmailsOfEmployeesInAllLowerDeptOfThisEmployeeInSiteLevelForMarketing(Set<String> marlketingPos,String reqSiteId);
	public List<ContractorTaxReportBean> getContractorTaxReport(Map<String, String> requestMap);
	
}
